spring:
  application:
    name: rabbitmq-learning
  rabbitmq:
    host: 39.98.174.58
    port: 5672
    username: ems
    password: 123
    virtual-host: /ems
    publisher-confirms: true #开启发送确认  消息发送的时候，有可能消息无法正常发送到rabbitmq情况
    publisher-returns: true #开启发送失败回退

    # 开启ack
    listener:
      topic:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
#        max-concurrency: 1 #指定最大的消费者数量
#        concurrency: 1 #指定最小的消费者数量
        prefetch: 5 #每个消费者每次监听时可拉取处理的消息数量
        retry:
          enabled: true #是否支持重试